config/routes.rb
Rails.application.routes.draw do
  resources :suppliers
  resources :products
  resources :tsupplierproducts
  resources :tcustomerproducts
  resources :customers

  get 'dashboard/home'
  root 'products#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tsupplierproduct.rb
class Tsupplierproduct < ApplicationRecord
  belongs_to :product
  belongs_to :supplier
end

app/controllers/tsupplierproducts_controller.rb
class TsupplierproductsController < ApplicationController
  before_action :set_tsupplierproduct, only: [:show, :edit, :update, :destroy]

  # GET /tsupplierproducts
  # GET /tsupplierproducts.json
  def index
    @tsupplierproducts = Tsupplierproduct.all
  end

  # GET /tsupplierproducts/1
  # GET /tsupplierproducts/1.json
  def show
  end

  # GET /tsupplierproducts/new
  def new
    @tsupplierproduct = Tsupplierproduct.new
  end

  # GET /tsupplierproducts/1/edit
  def edit
  end

  # POST /tsupplierproducts
  # POST /tsupplierproducts.json
  def create
    @tsupplierproduct = Tsupplierproduct.new(tsupplierproduct_params)

    respond_to do |format|
      if @tsupplierproduct.save
        format.html { redirect_to @tsupplierproduct, notice: 'Tsupplierproduct was successfully created.' }
        format.json { render :show, status: :created, location: @tsupplierproduct }
      else
        format.html { render :new }
        format.json { render json: @tsupplierproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tsupplierproducts/1
  # PATCH/PUT /tsupplierproducts/1.json
  def update
    respond_to do |format|
      if @tsupplierproduct.update(tsupplierproduct_params)
        format.html { redirect_to @tsupplierproduct, notice: 'Tsupplierproduct was successfully updated.' }
        format.json { render :show, status: :ok, location: @tsupplierproduct }
      else
        format.html { render :edit }
        format.json { render json: @tsupplierproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tsupplierproducts/1
  # DELETE /tsupplierproducts/1.json
  def destroy
    @tsupplierproduct.destroy
    respond_to do |format|
      format.html { redirect_to tsupplierproducts_url, notice: 'Tsupplierproduct was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tsupplierproduct
      @tsupplierproduct = Tsupplierproduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tsupplierproduct_params
      params.require(:tsupplierproduct).permit(:product_id, :supplier_id)
    end
end

app/helpers/tsupplierproducts_helper.rb
module TsupplierproductsHelper
end

app/views/tsupplierproducts/_form.html.erb
<%= form_with(model: tsupplierproduct, local: true) do |form| %>
  <% if tsupplierproduct.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tsupplierproduct.errors.count, "error") %> prohibited this tsupplierproduct from being saved:</h2>

      <ul>
      <% tsupplierproduct.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.collection_select :product_id, Product.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :supplier_id %>
    <%= form.collection_select :supplier_id, Supplier.all, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tsupplierproducts/edit.html.erb
<h1>Editing Tsupplierproduct</h1>

<%= render 'form', tsupplierproduct: @tsupplierproduct %>

<%= link_to 'Show', @tsupplierproduct %> |
<%= link_to 'Back', tsupplierproducts_path %>

app/views/tsupplierproducts/index.html.erb
<%= render 'layouts/header'  %>

<div class="container">

<p id="notice"><%= notice %></p>

<h1>Supplier P roducts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Supplier</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tsupplierproducts.each do |tsupplierproduct| %>
      <tr>
        <td><%= tsupplierproduct.supplier.name %></td>
        <td><%= tsupplierproduct.product.name %></td>
        <td><%= link_to 'Show', tsupplierproduct %></td>
        <td><%= link_to 'Edit', edit_tsupplierproduct_path(tsupplierproduct) %></td>
        <td><%= link_to 'Destroy', tsupplierproduct, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button class="btn btn-grey pull-right">
<%= link_to 'Create', new_tsupplierproduct_path %>
</button>

</div>

app/views/tsupplierproducts/new.html.erb
<h1>New Tsupplierproduct</h1>

<%= render 'form', tsupplierproduct: @tsupplierproduct %>

<%= link_to 'Back', tsupplierproducts_path %>

app/views/tsupplierproducts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Supplier:</strong>
  <%= @tsupplierproduct.supplier.name %>
</p>

<p>
  <strong>Product:</strong>
  <%= @tsupplierproduct.product.name %>
</p>

<%= link_to 'Edit', edit_tsupplierproduct_path(@tsupplierproduct) %> |
<%= link_to 'Back', tsupplierproducts_path %>