config/routes.rb
Rails.application.routes.draw do
  resources :suppliers
  resources :products
  resources :tsupplierproducts
  resources :tcustomerproducts
  resources :customers

  get 'dashboard/home'
  root 'products#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tcustomerproduct.rb
class Tcustomerproduct < ApplicationRecord
  belongs_to :product
  belongs_to :customer
end

app/controllers/tcustomerproducts_controller.rb
class TcustomerproductsController < ApplicationController
  before_action :set_tcustomerproduct, only: [:show, :edit, :update, :destroy]

  # GET /tcustomerproducts
  # GET /tcustomerproducts.json
  def index
    @tcustomerproducts = Tcustomerproduct.all
  end

  # GET /tcustomerproducts/1
  # GET /tcustomerproducts/1.json
  def show
  end

  # GET /tcustomerproducts/new
  def new
    @tcustomerproduct = Tcustomerproduct.new
  end

  # GET /tcustomerproducts/1/edit
  def edit
  end

  # POST /tcustomerproducts
  # POST /tcustomerproducts.json
  def create
    @tcustomerproduct = Tcustomerproduct.new(tcustomerproduct_params)

    respond_to do |format|
      if @tcustomerproduct.save
        format.html { redirect_to @tcustomerproduct, notice: 'Tcustomerproduct was successfully created.' }
        format.json { render :show, status: :created, location: @tcustomerproduct }
      else
        format.html { render :new }
        format.json { render json: @tcustomerproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tcustomerproducts/1
  # PATCH/PUT /tcustomerproducts/1.json
  def update
    respond_to do |format|
      if @tcustomerproduct.update(tcustomerproduct_params)
        format.html { redirect_to @tcustomerproduct, notice: 'Tcustomerproduct was successfully updated.' }
        format.json { render :show, status: :ok, location: @tcustomerproduct }
      else
        format.html { render :edit }
        format.json { render json: @tcustomerproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tcustomerproducts/1
  # DELETE /tcustomerproducts/1.json
  def destroy
    @tcustomerproduct.destroy
    respond_to do |format|
      format.html { redirect_to tcustomerproducts_url, notice: 'Tcustomerproduct was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tcustomerproduct
      @tcustomerproduct = Tcustomerproduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tcustomerproduct_params
      params.require(:tcustomerproduct).permit(:product_id, :customer_id)
    end
end

app/helpers/tcustomerproducts_helper.rb
module TcustomerproductsHelper
end

app/views/tcustomerproducts/_form.html.erb
<%= form_with(model: tcustomerproduct, local: true) do |form| %>
  <% if tcustomerproduct.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tcustomerproduct.errors.count, "error") %> prohibited this tcustomerproduct from being saved:</h2>

      <ul>
      <% tcustomerproduct.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.collection_select :customer_id,Customer.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.collection_select :product_id,Product.all, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tcustomerproducts/edit.html.erb
<h1>Editing Tcustomerproduct</h1>

<%= render 'form', tcustomerproduct: @tcustomerproduct %>

<%= link_to 'Show', @tcustomerproduct %> |
<%= link_to 'Back', tcustomerproducts_path %>

app/views/tcustomerproducts/index.html.erb
<%= render 'layouts/header'  %>

<div class="container">

<p id="notice"><%= notice %></p>

<h1>Customer Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Product</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tcustomerproducts.each do |tcustomerproduct| %>
      <tr>
        <td><%= tcustomerproduct.customer.name %></td>
        <td><%= tcustomerproduct.product.name %></td>
        <td><%= link_to 'Show', tcustomerproduct %></td>
        <td><%= link_to 'Edit', edit_tcustomerproduct_path(tcustomerproduct) %></td>
        <td><%= link_to 'Destroy', tcustomerproduct, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button class="btn btn-grey pull-right">
<%= link_to 'Create', new_tcustomerproduct_path %>
</button>

</div>

app/views/tcustomerproducts/new.html.erb
<h1>New Tcustomerproduct</h1>

<%= render 'form', tcustomerproduct: @tcustomerproduct %>

<%= link_to 'Back', tcustomerproducts_path %>

app/views/tcustomerproducts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @tcustomerproduct.customer.name %>
</p>

<p>
  <strong>Product:</strong>
  <%= @tcustomerproduct.product.name %>
</p>

<%= link_to 'Edit', edit_tcustomerproduct_path(@tcustomerproduct) %> |
<%= link_to 'Back', tcustomerproducts_path %>