config/routes.rb
Rails.application.routes.draw do
  resources :suppliers
  resources :products
  resources :tsupplierproducts
  resources :tcustomerproducts
  resources :customers

  get 'dashboard/home'
  root 'products#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= fontawesome_css_include_tag %>
    <%= boostrap_css_include_tag %>
    <%= boostrap_js_include_tag %>
    <%= bootswatch_css_include_tag %>
  </head>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button> 
      <a class="navbar-brand" href="#"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Product', products_url %><</li>
        <li><%= link_to 'Customer', customers_url %><</li>
        <li><%= link_to 'Supplier', suppliers_url %><</li>
        <li><%= link_to 'Customer Product ', tcustomerproducts_url %><</li>
        <li><%= link_to 'Supplier Product', tsupplierproducts_url %><</li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

 </html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppFirst</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>